### ISSUE TITLE
version 0.6.4 for terraform version 1.2.4 Error: Too many command line arguments

### ISSUE THREAD

**Issue by kimmxu** [AzBuilder/terraform-spring-boot#25]
The terraform client version 0.6.4 on version 1.2.4 terraform cli run error
"
Error: Too many command line arguments
Expected at most one positional argument.
For more help on using this command, run:
terraform apply -help
"

**Comment by alfespa17** [comment]
Can you provide an example @kimmxu to reproduce the issue?

**Comment by missedone** [comment]
@alfespa17 I have the same issue, it turns out the position of `tfplan` is incorrect

![image](https://user-images.githubusercontent.com/555134/218191664-bccf0c4b-a41f-493d-bbe8-f8d023948502.png)

it should be at the last
![image](https://user-images.githubusercontent.com/555134/218191865-78843f1d-f0a6-4f52-92f6-d053ed3313f1.png)

**Comment by alfespa17** [comment]
Hello @missedone can you provide a code example so I can reproduce the issue?

**Comment by missedone** [comment]
@alfespa17 , just updated my comment above, let me know if you need anything else

**Comment by alfespa17** [comment]
Thank you @missedone I will check code example and fix the issue in the library

**Comment by alfespa17** [comment]
I have created a new version to fix the issue @missedone, you can upgrade to 0.7.1. 

Feel free to open new issues if you find any other problem with the library
